all:
    hosts:
        k8s-master:
            ansible_host:
            ip: 10.10.1.31
            ansible_user: netology
            ansible_ssh_common_args: -J netology@89.169.150.5

        k8s-worker-1:
            ansible_host:
            ip: 10.10.1.15
            ansible_user: netology
            ansible_ssh_common_args: -J netology@89.169.150.5
        
        k8s-worker-2:
            ansible_host:
            ip: 10.10.2.14
            ansible_user: netology
            ansible_ssh_common_args: -J netology@89.169.150.5
         
        
        
kube_control_plane:
    hosts: 
        k8s-master:
kube_node:
    hosts:
        k8s-worker-1:
        k8s-worker-2:
etcd:
    hosts: 
        k8s-master: